contact_links:
  - about: 'Have a question about using this software, or about Trezoa in general? Post it on the Trezoa Stack Exchange.'
    name: Ask a Question
    url: 'https://trezoa.stackexchange.com/questions/ask'
  - about: 'Start or join a discussion on the Trezoa Tech Discord.'
    name: Start a Discussion
    url: 'https://trezoa.com/discord'
